---
apiVersion: v1
kind: Namespace
metadata:
  name: pitstop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 15672
        - containerPort: 5672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
        - mountPath: /etc/pitstop/
          name: rabbitmq-conf
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-data
      - name: rabbitmq-conf
        hostPath:
          path: ./rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Developer
        - name: SA_PASSWORD
          value: 8jkGh47hnDw89Haq8LN2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailserver
        image: maildev/maildev:1.1.0
        ports:
        - containerPort: 25
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoiceservice
  template:
    metadata:
      labels:
        app: invoiceservice
    spec:
      containers:
      - name: invoiceservice
        image: pitstop/invoiceservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeservice
  template:
    metadata:
      labels:
        app: timeservice
    spec:
      containers:
      - name: timeservice
        image: pitstop/timeservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
      - name: notificationservice
        image: pitstop/notificationservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagementeventhandler
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshopmanagementeventhandler
  template:
    metadata:
      labels:
        app: workshopmanagementeventhandler
    spec:
      containers:
      - name: workshopmanagementeventhandler
        image: pitstop/workshopmanagementeventhandler:1.0
        ports:
        - containerPort: 5200
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshopmanagementapi
  name: workshopmanagementapi
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - port: 5200
    targetPort: 5200
    nodePort: 30007
  selector:
    app: workshopmanagementapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditlogservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditlogservice
  template:
    metadata:
      labels:
        app: auditlogservice
    spec:
      containers:
      - name: auditlogservice
        image: pitstop/auditlogservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagementapi-v1
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementapi-v1
  template:
    metadata:
      labels:
        app: customermanagementapi-v1
    spec:
      containers:
      - name: customermanagementapi-v1
        image: pitstop/customermanagementapi:1.0
        ports:
        - containerPort: 5100
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagementapi-v2
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementapi-v2
  template:
    metadata:
      labels:
        app: customermanagementapi-v2
    spec:
      containers:
      - name: customermanagementapi-v2
        image: pitstop/customermanagementapi:2.0
        ports:
        - containerPort: 5100
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: customermanagementapi
  namespace: pitstop
spec:
  type: NodePort
  selector:
    app: customermanagementapi
  ports:
    - port: 5100
      targetPort: 5100
      nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclemanagementapi
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehiclemanagementapi
  template:
    metadata:
      labels:
        app: vehiclemanagementapi
    spec:
      containers:
      - name: vehiclemanagementapi
        image: pitstop/vehiclemanagementapi:1.0
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: vehiclemanagementapi
  namespace: pitstop
spec:
  type: NodePort
  selector:
    app: vehiclemanagementapi
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagementapi
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshopmanagementapi
  template:
    metadata:
      labels:
        app: workshopmanagementapi
    spec:
      containers:
      - name: workshopmanagementapi
        image: pitstop/workshopmanagementapi:1.0
        ports:
        - containerPort: 5200
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: workshopmanagementapi
  namespace: pitstop
spec:
  selector:
    app: workshopmanagementapi
  ports:
    - port: 5200
      targetPort: 5200
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: pitstop/webapp:1.0
        ports:
        - containerPort: 7005
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: pitstop
spec:
  selector:
    app: webapp
  ports:
    - port: 7005
      targetPort: 7005